/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pumpkin_platinum_DlanCore */

#ifndef _Included_com_pumpkin_platinum_DlanCore
#define _Included_com_pumpkin_platinum_DlanCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pumpkin_platinum_DlanCore
 * Method:    startMediaRender
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_pumpkin_platinum_DlanCore_startMediaRender
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_pumpkin_platinum_DlanCore
 * Method:    stopMediaRender
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pumpkin_platinum_DlanCore_stopMediaRender
  (JNIEnv *, jclass);

/*
 * Class:     com_pumpkin_platinum_DlanCore
 * Method:    respActionEvent
 * Signature: (I[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pumpkin_platinum_DlanCore_respActionEvent
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_pumpkin_platinum_DlanCore
 * Method:    enableLogPrint
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pumpkin_platinum_DlanCore_enableLogPrint
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
